### ISSUE TITLE
Occasional crash loops caused by events.ManagingOwner

### ISSUE THREAD

**Issue by ian659** [falcosecurity/k8s-metacollector#102]
**What happened**:
Pod occasionally crash loops. The pod will start, run for a minute, then fail.

```
{"level":"info","ts":"...","logger":"broker.grpc-server","msg":"received watch request","node":"...","subscriber UID":"..."}
{"level":"info","ts":"...","logger":"broker.grpc-server","msg":"starting initial event sync","node":"...","subscriber UID":"..."}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x156f81b]

goroutine 228 [running]:
github.com/falcosecurity/k8s-metacollector/pkg/events.ManagingOwner(...)
	/workspace/pkg/events/owner.go:25 github.com/falcosecurity/k8s-metacollector/collectors.dispatch.func1({0x1bff9b0, 0xc00008e0f0})
 	/workspace/collectors/dispatch.go:110 +0x13bb
created by github.com/falcosecurity/k8s-metacollector/collectors.dispatch in goroutine 206
	/workspace/collectors/dispatch.go:170 +0x33c
```

**What you expected to happen**:

Should not crash.

**How to reproduce it (as minimally and precisely as possible)**:

I have seen this happen a few times on different clusters. Eventually the crash loop will go away (presumably when the resource it is failing to handle is removed). I do not know the resource configuration that triggers this problem.

**Anything else we need to know?**:

The meta collector is deployed with the falco helm chart by setting `collectors.kubernetes.enabled`

My clusters are EKS v1.28.9-036c24b.

**Comment by alacuku** [comment]
Hi @ian659, thanks for reporting this issue. Hopefully, by the end of the day, I will fix the issue and release a new version of the k8s-metacollector.

**Comment by alacuku** [comment]
Hi @ian659, we just released a new version of Falco's chart that includes the fix. Please try it out and report back if the issue persists.

**Comment by alacuku** [comment]
Hey @ian659, did you try the new version?

**Comment by ian659** [comment]
@alacuku I've been running the new version on several clusters since late last week. I haven't recorded any crashes since then.

**Comment by ian659** [comment]
I believe this to be solved.
